# Generated by Django 5.0.6 on 2024-07-31 06:07

import django.db.models.deletion
import django.views.generic.edit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_amount_for_transfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMoneyView',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
            ],
            bases=('transactions.transaction', django.views.generic.edit.FormView),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
