# Generated by Django 5.0.6 on 2024-08-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transfermoneyview_alter_transaction_sender_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferMoneyView',
        ),
    ]
