# Generated by Django 5.0.6 on 2024-08-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_delete_transfermoneyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_bankrupt',
        ),
    ]
